In [1]:
from random import choice
from numpy import array,dot,random
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

Error Back Propagation to adjust weights in output layer and hidden layer

In [2]:
def sig_act(net):
  out=1/(1+np.exp(-net))
  return out

In [3]:
#X-OR (Linearly Non-separable)
random.seed(5)
w=random.rand(3,3)
train_data=[(array([0,0,1]),0),(array([0,1,1]),1),(array([1,0,1]),1),(array([1,1,1]),0)]
v=random.rand(4,1)
eta=0.01

In [4]:
train_data

[(array([0, 0, 1]), 0),
 (array([0, 1, 1]), 1),
 (array([1, 0, 1]), 1),
 (array([1, 1, 1]), 0)]

In [5]:
w

array([[0.22199317, 0.87073231, 0.20671916],
       [0.91861091, 0.48841119, 0.61174386],
       [0.76590786, 0.51841799, 0.2968005 ]])

In [6]:
v

array([[0.18772123],
       [0.08074127],
       [0.7384403 ],
       [0.44130922]])

In [7]:
x,expected=choice(train_data)


In [8]:
x

array([1, 0, 1])

In [ ]:
expected

1

In [9]:
net1=dot(x,w)
net1

array([0.98790103, 1.38915029, 0.50351966])

In [10]:
y=sig_act(net1)
y

array([0.72867314, 0.80045656, 0.62328611])

In [ ]:
y*(1-y)

array([0.21664445, 0.2339274 , 0.24457418])

In [ ]:
v

array([[0.18772123],
       [0.08074127],
       [0.7384403 ],
       [0.44130922]])

In [11]:
#Hidden Layer to output layer ff flow
bias=np.array([1])
y_in=np.concatenate((y,bias),axis=0)
y_in

array([0.72867314, 0.80045656, 0.62328611, 1.        ])

In [12]:
net2=dot(y_in,v)
net2

array([1.10298609])

In [13]:
y_pred=sig_act(net2)
y_pred

array([0.75081919])

In [14]:
#Error_grad at the output layer
delta_out=(expected-y_pred)*y_pred*(1-y_pred)
delta_out

array([0.04661917])

In [15]:
x.reshape(-1,1)

array([[1],
       [0],
       [1]])

In [16]:
v=v+(eta*delta_out*y_in.reshape(-1,1))

In [17]:
v

array([[0.18806093],
       [0.08111443],
       [0.73873087],
       [0.44177541]])

In [ ]:
y

array([0.87062677, 0.86733078, 0.75310909])

In [ ]:
1-y

array([0.12937323, 0.13266922, 0.24689091])

In [19]:
y_dash=y*(1-y)
y_dash.reshape(-1,1)

array([[0.1977086 ],
       [0.15972586],
       [0.23480054]])

In [ ]:
y_dash

array([0.11263579, 0.1150681 , 0.18593579])

In [18]:
#output side delta back propagate to hidden layer
bp=delta_out*v[:3]
bp

array([[0.00876724],
       [0.00378149],
       [0.03443902]])

In [21]:
#calculating hidden layer delta
delta_hid=np.multiply(y_dash.reshape(-1,1),bp)
delta_hid

array([[0.00173336],
       [0.000604  ],
       [0.0080863 ]])

In [ ]:
w

array([[0.22199317, 0.87073231, 0.20671916],
       [0.91861091, 0.48841119, 0.61174386],
       [0.76590786, 0.51841799, 0.2968005 ]])

In [ ]:
eta*delta_hid[0]

array([-0.00054931])

In [ ]:
x

array([1, 1, 1])

In [22]:
w[:,0]=w[:,0]+(eta*delta_hid[0]*x)
w[:,1]=w[:,1]+(eta*delta_hid[1]*x)
w[:,2]=w[:,2]+(eta*delta_hid[2]*x)

In [ ]:
w[:,0]

array([0.22199317, 0.91861091, 0.76590786])

In [ ]:
choice(train_data)

(array([0, 1, 1]), 1)

In [41]:
#XOR (linearly non-separable problem)
train_data=[(array([0,0,1]),0),(array([0,1,1]),1),(array([1,0,1]),1),(array([1,1,1]),0)]
v=random.rand(3,3) #weights connecting input to hidden layer
w=random.rand(4,1)#weights connecting hidden to output layer
eta=0.45
n=15000
#Training
for i in range(n):
  x,expected=choice(train_data)
  net1=dot(x,v)
  y=sig_act(net1) #hidden layer output
  bias=np.array([1]) #input to bias at output layer
  y_in=np.concatenate((y,bias),axis=0)
  net2=dot(y_in,w)
  y_pred=sig_act(net2) #output layer response
  delta_out=(expected-y_pred)*y_pred*(1-y_pred) #output layer error gradient
  w=w+(eta*delta_out*y_in.reshape(-1,1)) # updating the Hidden-Output weight matrix
  #Output error propagates to hidden layer
  bp=delta_out*w[:3]
  y_dash=y*(1-y)
  y_dash.reshape(-1,1)
  delta_hid=np.multiply(y_dash.reshape(-1,1),bp)
  v[:,0]=v[:,0]+(eta*delta_hid[0]*x)
  v[:,1]=v[:,1]+(eta*delta_hid[1]*x)
  v[:,2]=v[:,2]+(eta*delta_hid[2]*x)

In [24]:
w

array([[ 0.12225032],
       [ 0.08449913],
       [ 0.17702901],
       [-0.09359034]])

In [25]:
v

array([[0.15605152, 0.87874824, 0.27212136],
       [0.41165384, 0.2970442 , 0.62610244],
       [0.56976384, 0.59262321, 0.25325468]])

In [ ]:
#train_data=[(array([0.2,0.3,1]),0),(array([0,.8,1]),1),(array([.7,0,1]),1),(array([.8,.75,1]),0)]

In [42]:
#Testing (feedforward flow only)
for x,_ in train_data:
  net1=dot(x,v)
  y=sig_act(net1) #(3x1)
  bias=np.array([1]) #input to bias at output layer
  y_in=np.concatenate((y,bias),axis=0)
  net2=dot(y_in,w)
  y_pred=sig_act(net2)
  print("{} :-> {}".format(x[:3],y_pred))

[0 0 1] :-> [0.03965356]
[0 1 1] :-> [0.96708234]
[1 0 1] :-> [0.96532844]
[1 1 1] :-> [0.03809788]


In [43]:
v

array([[ 1.19054791,  3.68846701,  6.4046902 ],
       [ 0.92026464,  3.85977551,  6.29025991],
       [-1.38337819, -5.80511317, -2.75087184]])

In [44]:
net1=dot(np.array([0,0,0]),v)
y=sig_act(net1)
y

array([0.5, 0.5, 0.5])

In [45]:
net1=dot(np.array([0,1,1]),v)
y=sig_act(net1)
y

array([0.38624746, 0.12506263, 0.97178794])

In [46]:
net1=dot(np.array([1,0,1]),v)
y=sig_act(net1)
y

array([0.45194125, 0.1074894 , 0.97476141])

In [47]:
net1=dot(np.array([1,1,1]),v)
y=sig_act(net1)
y

array([0.67424201, 0.85108412, 0.99995199])

In [48]:
hidden_neurons1=np.array([[0.5, 0.5, 0.5],[0.38624746, 0.12506263, 0.97178794],[0.45194125, 0.1074894 , 0.97476141],[0.67424201, 0.85108412, 0.99995199]])
hidden_neurons1

array([[0.5       , 0.5       , 0.5       ],
       [0.38624746, 0.12506263, 0.97178794],
       [0.45194125, 0.1074894 , 0.97476141],
       [0.67424201, 0.85108412, 0.99995199]])

In [ ]:
hidden_neurons=np.array([[0.00096747, 0.22304379, 0.06294064],[0.08597616, 0.91880635, 0.97109102],[0.08711226, 0.92458436, 0.97241896],[0.90261745, 0.99793505, 0.99994329]])
hidden_neurons

array([[9.6747000e-04, 2.2304379e-01, 6.2940640e-02],
       [8.5976160e-02, 9.1880635e-01, 9.7109102e-01],
       [8.7112260e-02, 9.2458436e-01, 9.7241896e-01],
       [9.0261745e-01, 9.9793505e-01, 9.9994329e-01]])

In [50]:
input_feat=np.array([[0, 0, 1],[0, 1, 1],[1   , 0, 1],[1, 1, 1]])
input_feat

array([[0, 0, 1],
       [0, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [49]:
import pandas as pd
HN=pd.DataFrame(hidden_neurons1,columns=['H1','H2','H3'])
HN

H1        H2        H3
0  0.500000  0.500000  0.500000
1  0.386247  0.125063  0.971788
2  0.451941  0.107489  0.974761
3  0.674242  0.851084  0.999952

In [51]:
IP=pd.DataFrame(input_feat,columns=['X1','X2','XB'])
IP

X1  X2  XB
0   0   0   1
1   0   1   1
2   1   0   1
3   1   1   1

In [52]:
IP['label']=['0','1','1','0']
IP

X1  X2  XB label
0   0   0   1     0
1   0   1   1     1
2   1   0   1     1
3   1   1   1     0

In [53]:
HN['label']=['0','1','1','0']
HN

H1        H2        H3 label
0  0.500000  0.500000  0.500000     0
1  0.386247  0.125063  0.971788     1
2  0.451941  0.107489  0.974761     1
3  0.674242  0.851084  0.999952     0

In [54]:
# 3D scatter plot
import plotly.express as px
fig = px.scatter_3d(HN, x='H1', y='H2', z='H3',color=HN.label)
fig.show()

In [55]:
fig = px.scatter_3d(IP, x='X1', y='X2', z='XB',color=HN.label)
fig.show()

In [ ]:
v

array([[ 7.60696357],
       [-6.1595104 ],
       [-6.21165268],
       [ 1.86591419]])

In [ ]:
net2=dot(np.array([0.26051543, 0.80340231, 0.41571272,1]),v)
y_pred=sig_act(net2)
y_pred

array([0.02452618])

In [ ]:
net2=dot(np.array([0.99086226, 0.99955096, 0.09183151,1]),v)
y_pred=sig_act(net2)
y_pred

array([0.93560741])

In [ ]:
net2=dot(np.array([0.97754   , 0.0706186 , 0.99405969,1]),v)
y_pred=sig_act(net2)
y_pred

array([0.9365705])

In [ ]:
net2=dot(np.array([0.99992536, 0.97640925, 0.95964936,1]),v)
y_pred=sig_act(net2)
y_pred

array([0.07565503])