In [1]:
from random import choice
from numpy import array,dot,random
import numpy as np

In [ ]:
#random.seed(10)

In [17]:
w=random.rand(2)  #fixed weights with no scope for learning
w

array([0.42220259, 0.17266126])

In [ ]:
w

array([0.15600494, 0.70008017])

In [25]:
#Mcculloch-Pitts Model for AND gate
#w=random.rand(2)
#w[0]=1
#w[1]=1
print(w)
train_data=[(array([0,0]),0),(array([0,1]),1),(array([1,0]),1),(array([1,1]),1)]
train_data

[0.42220259 0.17266126]


[(array([0, 0]), 0),
 (array([0, 1]), 1),
 (array([1, 0]), 1),
 (array([1, 1]), 1)]

In [ ]:
w

array([0.76978166, 0.49628126])

In [21]:
#Hard Limit Activation Function (HLAF)
def my_act(net):
  if net<0.5:
    return(0)
  else:
    return(1)

In [10]:
my_act(0.9)

1

In [27]:
#Threshold based activation (Hard Limit Activation Function)
act_function= lambda net: 0 if net<0.1 else 1

In [28]:
for x,_ in train_data:
  net=dot(x,w) #net value
  print("{} : {} -> {}".format(x[:2],net,act_function(net)))

[0 0] : 0.0 -> 0
[0 1] : 0.17266126225338851 -> 1
[1 0] : 0.4222025866940854 -> 1
[1 1] : 0.5948638489474739 -> 1


In [ ]:
w

array([0.32285895, 0.82592435])

In [ ]:
#Mcculloch-Pitts Model for OR gate
#w=random.rand(2)
#w[0]=0.25
#w[1]=0.08
print(w)
train_data=[(array([0,0]),0),(array([0,1]),1),(array([1,0]),1),(array([1,1]),1)]
train_data

[0.54049948 0.89781585]


[(array([0, 0]), 0),
 (array([0, 1]), 1),
 (array([1, 0]), 1),
 (array([1, 1]), 1)]

In [ ]:
w

array([1., 1.])

In [ ]:
act_function= lambda net: 0 if net<0.25 else 1

In [ ]:
for x,_ in train_data:
  result=dot(x,w)
  print("{} : {} -> {}".format(x[:2],result,act_function(result)))

[0 0] : 0.0 -> 0
[0 1] : 0.8978158522550334 -> 1
[1 0] : 0.5404994794611601 -> 1
[1 1] : 1.4383153317161934 -> 1


Rosenblat's Neuron : Instead of using fixed weight with no learning scope, he introduced random weights and bias with learning scope

In [132]:
#assign a random threshold value
act_function= lambda x: 0 if x<=1.5 else 1
train_data=[(array([0,0,1]),0),(array([0,1,1]),1),(array([1,0,1]),1),(array([1,1,1]),0)]
#random.seed(10)
w=random.rand(3)
#w=np.array([0.51416544, 0.34653827, 0.01031072])
eta=0.1

In [120]:
print(w)

[0.74880388 0.49850701 0.22479665]


In [133]:
train_data

[(array([0, 0, 1]), 0),
 (array([0, 1, 1]), 1),
 (array([1, 0, 1]), 1),
 (array([1, 1, 1]), 0)]

In [37]:
x,expected=choice(train_data)
print(x,expected)

[1 1 1] 1


In [38]:
dot(w,x)

1.425720827552423

In [39]:
act_function(dot(w,x))

0

In [140]:
#Stochastic Gradient Descent
errors=[]
n=50000
#Training
for i in range(n):
  x,expected=choice(train_data) #replace the choice function and access the data in order (1 to 4)
  net=dot(w,x)   #sum of products
  y_pred=act_function(net)  #predicted output
  error=expected-y_pred   # individual error gradient
  errors.append(error)
  w+=eta*error*x

In [82]:
w

array([0.37132064, 0.82075195, 0.23364823])

In [126]:
#Full Batch Gradient Descent
epoch=50000
#Training
for i in range(epoch):
  error_grad=0
  for j in range(len(train_data)):
    x,expected=train_data[j]
    net=dot(w,x)   #sum of products
    y_pred=act_function(net)  #predicted output
    error=expected-y_pred   # individual error gradient
    error_grad+=error
  w+=eta*error_grad*x

In [94]:
w

array([0.77132064, 0.02075195, 0.63364823])

In [ ]:
w

array([1.27132064, 0.72075195, 1.83364823])

In [141]:
#Testing
for x,_ in train_data:
  net=dot(x,w)
  print("{} : {} -> {}".format(x[:3],net,act_function(net)))

[0 0 1] : 1.512620961652114 -> 1
[0 1 1] : 1.5248132250378907 -> 1
[1 0 1] : 1.4165692279800286 -> 0
[1 1 1] : 1.428761491365805 -> 0


In [ ]:
w

array([ 0.35080833, -0.34002011,  4.82160698])